object Versions {
    const val gradlePlugin = "7.2.2"
    const val kotlin = "1.7.10"

    const val core = "1.9.0"
    const val appCompat = "1.5.1"
    const val constraintLayout = "2.1.4"
    const val recyclerView = "1.2.1"
    const val lifecycle = "2.5.1"
    const val activity = "1.5.1"
    const val fragment = "1.5.2"
    const val navigation = "2.5.2"
    const val paging = "3.1.1"
    const val material = "1.6.1"
    const val hilt = "2.43.2"
    const val okhttp = "4.10.0"
    const val retrofit = "2.9.0"
    const val moshi = "1.14.0"
    const val coroutines = "1.6.4"
    const val coil = "2.2.1"
    const val timber = "5.0.1"

    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.3"
    const val espresso = "3.4.0"
}
